#!/bin/zsh

# ==============================================================================
# 🤖 Agent Artifact Builder (v5.0 - Static Build)
# ==============================================================================
# 1. .env 파일 로드
# 2. 모든 모드(modes/*)에 대해 Master 파일 생성 (build/master_{mode}.md)
# 3. Core Skills (core/*) 병합
# ==============================================================================

# 1. 경로 설정
# 스크립트가 scripts/ 디렉토리에 있으므로, 부모 디렉토리를 AGENT_ROOT로 설정
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENT_ROOT="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$AGENT_ROOT/build"
ENV_FILE="$AGENT_ROOT/.env"

# 2. 색상 설정
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}=== 🤖 Agent Artifact Build Start ===${NC}"

# 3. 환경 설정 로드
if [[ -f "$ENV_FILE" ]]; then
    source "$ENV_FILE"
    echo -e "    ⚙️  설정 로드됨: ${YELLOW}.env${NC}"
else
    echo -e "${YELLOW}⚠️  .env 파일을 찾을 수 없습니다. 기본값을 사용합니다.${NC}"
    [[ -z "$GH_HOST" ]] && GH_HOST="github.com"
fi

echo -e "    🌐 GitHub 호스트: ${YELLOW}$GH_HOST${NC}"

# 4. 빌드 디렉토리 준비
if [[ ! -d "$BUILD_DIR" ]]; then
    mkdir -p "$BUILD_DIR"
    echo -e "    📂 Build 디렉토리 생성: $BUILD_DIR"
fi

# ------------------------------------------------------------------------------
# 전역 함수: 파일 병합 및 치환
# ------------------------------------------------------------------------------
append_and_replace() {
    local source_file=$1
    local target_file=$2

    # sed를 사용하여 Placeholder 치환 후 Master 파일에 추가
    cat "$source_file" | \
        sed "s|{{GH_HOST}}|$GH_HOST|g" | \
        sed "s|{{AGENT_ROOT}}|$AGENT_ROOT|g" >> "$target_file"
    echo -e "\n\n---\n\n" >> "$target_file"
}

# ------------------------------------------------------------------------------
# 함수: Master 파일 생성
# ------------------------------------------------------------------------------
build_master_file() {
    local mode_name=$1
    local mode_dir=$2
    local output_file="$BUILD_DIR/master_${mode_name}.md"

    echo -e "\n${YELLOW}[Build] ${mode_name} Mode...${NC}"

    # 헤더 생성
    cat > "$output_file" << EOF
# 🤖 Master Agent Instructions ($mode_name Mode)
# Auto-generated by sync_agent.sh
# DO NOT EDIT THIS FILE DIRECTLY - Edit source files instead
# ==============================================================================

EOF

    # 파일 확인
    if [[ ! -f "$output_file" ]]; then
        echo -e "${RED}❌ Error: Target file '$output_file' does not exist.${NC}"
        return
    fi


    # 1. Mode Specific Instructions
    if [[ -d "$AGENT_ROOT/$mode_dir" ]]; then
        for file in $(find "$AGENT_ROOT/$mode_dir" -maxdepth 1 -name "*.md" -type f | sort); do
            echo -e "       ✓ Instructions: $(basename "$file")"
            append_and_replace "$file" "$output_file"
        done
    else
        echo -e "${RED}❌ 오류: 모드 디렉토리를 찾을 수 없습니다: $mode_dir${NC}"
        return
    fi

    # 2. Core Skills
    for file in $(find "$AGENT_ROOT/core" -maxdepth 1 -name "*.md" -type f | sort); do
        echo -e "       ✓ Core Skill: $(basename "$file")"
        append_and_replace "$file" "$output_file"
    done

    echo -e "    ✅ Artifact 생성 완료: ${GREEN}$(basename "$output_file")${NC}"
}

# ------------------------------------------------------------------------------
# Step 1: 모든 모드 빌드
# ------------------------------------------------------------------------------

# Define modes mapping (Directory -> Name suffix)
# modes/dev -> dev
# modes/plan -> plan
# modes/code-review -> review
# modes/test -> test
# modes/doc -> doc

build_master_file "dev" "modes/dev"
build_master_file "plan" "modes/plan"
build_master_file "review" "modes/code-review"
build_master_file "test" "modes/test"
build_master_file "doc" "modes/doc"

# ==============================================================================
# 5. 동적 마스터 파일 생성 (master_dynamic.md)
# ==============================================================================
# 설명: 모든 모드를 포함하지 않고, 필요 시 찾아볼 수 있는 '지도(Map)'만 포함한 경량화/유연화 버전
TARGET_DYNAMIC="$BUILD_DIR/master_dynamic.md"
echo -e "\n${YELLOW}[Build] dynamic Mode...${NC}"

# 5.1 헤더
cat > "$TARGET_DYNAMIC" << EOF
# 🤖 Master Agent Instructions (Dynamic Mode)
# Auto-generated by sync_agent.sh
# ==============================================================================

EOF

# 5.2 공통 지침 (instructions/)
# 00~05 (Rules) + 99 (Capability Map)
    for file in $(find "$AGENT_ROOT/instructions" -maxdepth 1 -name "*.md" -type f | sort); do
        echo -e "       ✓ Instructions: $(basename "$file")"
        append_and_replace "$file" "$TARGET_DYNAMIC"
    done

    if [[ -d "$AGENT_ROOT/core" ]]; then
        for file in $(find "$AGENT_ROOT/core" -maxdepth 1 -name "*.md" -type f ! -name "12_bootstrap.md" | sort); do
             echo -e "       ✓ Core Skill: $(basename "$file")"
             append_and_replace "$file" "$TARGET_DYNAMIC"
        done
    fi

echo -e "    ✅ Artifact 생성 완료: ${GREEN}master_dynamic.md${NC}"


echo -e "    ✅ Artifact 생성 완료: ${GREEN}master_dynamic.md${NC}"

# ==============================================================================
# 6. 배포 및 연결 (Deployment & Linking)
# ==============================================================================
# "Dynamic Mode"를 기본으로 하여 모든 에이전트를 연결합니다.
# 빌드 후 즉시 배포됩니다.

TARGET_MODE="dynamic"
SOURCE_FILE="$BUILD_DIR/master_${TARGET_MODE}.md"

if [[ ! -f "$SOURCE_FILE" ]]; then
    echo -e "${RED}❌ Critical Error: Master dynamic file not found!${NC}"
    exit 1
fi

echo -e "\n${BLUE}=== 🚀 Deploying '${TARGET_MODE}' Agent ===${NC}"

# SCAN_PATH 기본값 설정
if [[ -z "$SCAN_PATH" ]]; then
    SCAN_PATH="$HOME/git"
    echo -e "    ⚠️  SCAN_PATH not set, defaulting to: ${YELLOW}$SCAN_PATH${NC}"
fi

# ------------------------------------------------------------------------------
# 배포 함수 정의
# ------------------------------------------------------------------------------
update_symlink() {
    local target_path=$1
    local link_source=$2
    local target_dir=$(dirname "$target_path")

    # 디렉토리 없으면 생성
    [[ ! -d "$target_dir" ]] && mkdir -p "$target_dir"

    # 기존 링크/파일 제거 (백업 없이 강제 교체)
    rm -f "$target_path"
    
    # 새 링크 생성
    ln -s "$link_source" "$target_path"
}

ensure_gitignore() {
    local project_root=$1
    local target_file=$2
    local gitignore="$project_root/.gitignore"
    
    # .gitignore가 존재하는 경우에만 처리
    if [[ -f "$gitignore" ]]; then
        if ! grep -qFx "$target_file" "$gitignore"; then
            echo "" >> "$gitignore"
            echo "$target_file" >> "$gitignore"
            echo -e "    🙈 Added to .gitignore: ${YELLOW}$target_file${NC}"
        fi
    fi
}

update_project_link() {
    local git_dir=$1
    local project_root="${git_dir:h}"   # Zsh modifier
    
    # 대상 정의
    local targets=(
        ".github/copilot-instructions.md"
        ".cursorrules"
        ".clinerules"
        ".windsurfrules"
        ".opencode/AGENTS.md"
    )
    
    for rel_path in "${targets[@]}"; do
        local full_path="$project_root/$rel_path"
        update_symlink "$full_path" "$SOURCE_FILE"
        ensure_gitignore "$project_root" "$rel_path"
    done

    ((COUNT++))
}

# 6.1 ~/.gemini/GEMINI.md 업데이트
update_symlink "$HOME/.gemini/GEMINI.md" "$SOURCE_FILE"
echo -e "✅ Global Agent Updated: ${YELLOW}~/.gemini/GEMINI.md${NC}"

# 6.1.1 OpenCode global instructions
update_symlink "$HOME/.config/opencode/AGENTS.md" "$SOURCE_FILE"
echo -e "✅ OpenCode Agent Updated: ${YELLOW}~/.config/opencode/AGENTS.md${NC}"

# 6.2 Git 프로젝트 스캔 및 업데이트
if [[ -d "$SCAN_PATH" ]]; then
    echo -e "🔍 Scanning projects in ${YELLOW}$SCAN_PATH${NC}..."
    COUNT=0
    
    if command -v fd &> /dev/null; then
        fd -H -t d "^\.git$" "$SCAN_PATH" --prune \
            --exclude "node_modules" --exclude ".Trash" --exclude "build" --exclude "target" \
        | while read git_dir; do update_project_link "$git_dir"; done
    else
         find "$SCAN_PATH" -type d -name ".git" -prune | while read git_dir; do update_project_link "$git_dir"; done
    fi

    # 6.3 Self-Update (Dogfooding)
    update_project_link "$AGENT_ROOT/.git"
    
    echo -e "✅ Updated ${GREEN}$COUNT${NC} projects to use 'dynamic' capability map."
fi

# 7. 상태 저장 (links.map) - 하위 호환성 유지
echo "GLOBAL=$TARGET_MODE" > "$AGENT_ROOT/links.map"

echo -e "\n${BLUE}=== 🎉 All Done ===${NC}"
echo -e "빌드와 배포가 완료되었습니다. 에이전트는 이제 스스로 지침을 탐색합니다."
